# Generated by Django 4.2.21 on 2025-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
