# Generated by Django 4.2.21 on 2025-06-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='skill.department'),
        ),
    ]
