# Generated by Django 4.2.21 on 2025-06-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
