
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: unimarkt
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DB_NAME: unimarkt
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
