version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: unimarkt
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"  # Expose Redis port
    restart: always

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DB_NAME: unimarkt
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

volumes:
  db_data:
