# Generated by Django 4.2.21 on 2025-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
