# Generated by Django 4.2.21 on 2025-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skill_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletimeslot',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('booked', 'Booked')], default='open', max_length=10),
        ),
    ]
