# Generated by Django 4.2.21 on 2025-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skill_isarchived'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
