# Generated by Django 4.2.21 on 2025-06-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('security_question1', models.CharField(blank=True, choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', "What was your first pet's name?"), ('favorite_book', 'What is your favorite book?')], max_length=50, null=True)),
                ('answer1', models.CharField(max_length=255)),
                ('security_question2', models.CharField(blank=True, choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', "What was your first pet's name?"), ('favorite_book', 'What is your favorite book?')], max_length=50, null=True)),
                ('answer2', models.CharField(blank=True, max_length=255, null=True)),
                ('security_question3', models.CharField(blank=True, choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', "What was your first pet's name?"), ('favorite_book', 'What is your favorite book?')], max_length=50, null=True)),
                ('answer3', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniMarktAuth.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
