# Generated by Django 4.2.21 on 2025-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniMarktAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answer1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='answer3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
