# Generated by Django 4.2.21 on 2025-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='color',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='default_value', max_length=100),
        ),
    ]
