# Generated by Django 4.2.21 on 2025-06-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
