# Generated by Django 4.2.21 on 2025-05-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_created_date_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
