# Generated by Django 4.2.21 on 2025-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_created_date_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
