# Generated by Django 4.2.21 on 2025-08-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage or amount', max_digits=10, null=True),
        ),
    ]
