import { Job } from "@/modules/jobs/types";

export const jobs: Job[] = [
  {
    job_id: "job_001",
    title: "Research Assistant in AI",
    description:
      "Assist in AI-related research including data preprocessing and model training.",
    remuneration: 1200,
    department: { id: "dept_ai", name: "Artificial Intelligence" },
    department_id: "dept_ai",
    job_type: "research",
    contact_email: "dr.ai@university.edu",
    contact_name: "Dr. Alice Neumann",
    contact_phone: "+49 123 4567890",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "approved",
    isArchived: false,
    created_at: "2025-06-01T10:00:00Z",
    updated_at: "2025-06-05T12:00:00Z",
  },
  {
    job_id: "job_002",
    title: "HiWi for Software Engineering Course",
    description:
      "Support the Software Engineering course by assisting students and maintaining materials.",
    remuneration: 900,
    department: { id: "dept_se", name: "Software Engineering" },
    department_id: "dept_se",
    job_type: "hiwi",
    contact_email: "prof.se@university.edu",
    contact_name: "Prof. Markus Lang",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "pending",
    isArchived: false,
    created_at: "2025-06-10T14:15:00Z",
    updated_at: "2025-06-11T08:00:00Z",
  },
  {
    job_id: "job_003",
    title: "Tutor for Calculus I",
    description: "Lead weekly tutorial sessions for Calculus I students.",
    remuneration: 800,
    department: { id: "dept_math", name: "Mathematics" },
    department_id: "dept_math",
    job_type: "tutoring",
    contact_email: "math.tutor@university.edu",
    contact_name: "Laura Schmidt",
    contact_phone: "+49 234 5678901",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "approved",
    isArchived: false,
    created_at: "2025-06-02T09:00:00Z",
    updated_at: "2025-06-06T10:30:00Z",
  },
  {
    job_id: "job_004",
    title: "Admin Support for Exam Office",
    description: "Help organize and digitize student exam records.",
    remuneration: 700,
    department: { id: "dept_admin", name: "Administration" },
    department_id: "dept_admin",
    job_type: "administrative",
    contact_email: "admin.office@university.edu",
    contact_name: "Johannes Becker",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "approved",
    isArchived: false,
    created_at: "2025-06-03T08:30:00Z",
    updated_at: "2025-06-03T08:30:00Z",
  },
  {
    job_id: "job_005",
    title: "HiWi for Database Systems Lab",
    description: "Assist students in lab sessions and evaluate their projects.",
    remuneration: 950,
    department: { id: "dept_db", name: "Database Systems" },
    department_id: "dept_db",
    job_type: "hiwi",
    contact_email: "db.lab@university.edu",
    contact_name: "Sandra Keller",
    contact_phone: "+49 345 6789012",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "pending",
    isArchived: false,
    created_at: "2025-06-04T11:00:00Z",
    updated_at: "2025-06-05T13:00:00Z",
  },
  {
    job_id: "job_006",
    title: "Research Intern - Computer Vision",
    description:
      "Work on developing object detection models for smart surveillance.",
    remuneration: 1300,
    department: { id: "dept_cv", name: "Computer Vision" },
    department_id: "dept_cv",
    job_type: "research",
    contact_email: "cv.research@university.edu",
    contact_name: "Dr. Michael Hartmann",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "approved",
    isArchived: false,
    created_at: "2025-06-06T10:00:00Z",
    updated_at: "2025-06-06T10:00:00Z",
  },
  {
    job_id: "job_007",
    title: "Part-time Admin for Student Services",
    description: "Assist with student inquiries and maintain records.",
    remuneration: 600,
    department: { id: "dept_stud", name: "Student Services" },
    department_id: "dept_stud",
    job_type: "administrative",
    contact_email: "student.services@university.edu",
    contact_name: "Nina Köhler",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "approved",
    isArchived: true,
    created_at: "2025-05-30T15:00:00Z",
    updated_at: "2025-06-01T16:00:00Z",
  },
  {
    job_id: "job_008",
    title: "Tutoring Assistant - Intro to Programming",
    description: "Hold tutoring sessions and help beginners with Python.",
    remuneration: 850,
    department: { id: "dept_prog", name: "Computer Science Basics" },
    department_id: "dept_prog",
    job_type: "tutoring",
    contact_email: "prog.tutor@university.edu",
    contact_name: "Thomas Weber",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "approved",
    isArchived: false,
    created_at: "2025-06-07T13:00:00Z",
    updated_at: "2025-06-08T10:00:00Z",
  },
  {
    job_id: "job_009",
    title: "Event Coordinator Support (HiWi)",
    description:
      "Support university events including logistics and communication.",
    remuneration: 750,
    department: { id: "dept_events", name: "Event Management" },
    department_id: "dept_events",
    job_type: "hiwi",
    contact_email: "events@university.edu",
    contact_name: "Eva Braun",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "pending",
    isArchived: false,
    created_at: "2025-06-09T09:45:00Z",
    updated_at: "2025-06-09T09:45:00Z",
  },
  {
    job_id: "job_010",
    title: "General IT Support",
    description:
      "Help the IT department with system maintenance and user support.",
    remuneration: 1000,
    department: { id: "dept_it", name: "IT Services" },
    department_id: "dept_it",
    job_type: "other",
    contact_email: "it.support@university.edu",
    contact_name: "Sebastian Krüger",
    contact_phone: "+49 456 7890123",
    posted_by: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
      role: 2,
    },
    status: "rejected",
    isArchived: false,
    created_at: "2025-06-01T08:00:00Z",
    updated_at: "2025-06-12T14:00:00Z",
  },
];

export const job: Job = {
  job_id: "job_001",
  title: "Research Assistant in AI",
  description:
    "Assist in AI-related research including data preprocessing and model training.",
  remuneration: 1200,
  department: { id: "dept_ai", name: "Artificial Intelligence" },
  department_id: "dept_ai",
  job_type: "research",
  contact_email: "dr.ai@university.edu",
  contact_name: "Dr. Alice Neumann",
  contact_phone: "+49 123 4567890",
  posted_by: {
    id: "2",
    name: "Bob Lee",
    email: "bob@example.com",
    contact_number: "0987654321",
    role: 2,
  },
  status: "approved",
  isArchived: false,
  created_at: "2025-06-01T10:00:00Z",
  updated_at: "2025-06-05T12:00:00Z",
};
