import { Product } from "@/modules/products/types";
import { categories } from "./product-categories";

export const products: Product[] = [
  {
    product_id: "23",
    name: "Hollee Velez product 2",
    category: {
      id: "5",
      name: "Furniture",
      color: "#A52A2A",
      slug: "furniture",
      category_id: "5",
      subcategories: [
        {
          id: "4",
          name: "Office Furniture",
          color: undefined,
          slug: "office-furniture",
          category_id: "5",
          subcategories: [],
        },
        {
          id: "9",
          name: "Home Furniture",
          color: undefined,
          slug: "home-furniture",
          category_id: "5",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "4",
      name: "Office Furniture",
      color: undefined,
      slug: "office-furniture",
      category_id: "5",
      subcategories: [],
    },
    description: "Quibusdam minus sed",
    price: "628.00",
    images: [
      "https://unimarkt-bucket.s3.eu-central-1.amazonaws.com/uploads/cabdcff9-ab3f-40fe-9294-a4c64fd9dba4_Screenshot 2025-05-04 at 11.10.00 AM.png",
      "https://unimarkt-bucket.s3.eu-central-1.amazonaws.com/uploads/e3f7b8e1-969e-48f3-ad8d-6b8e166fc830_Screenshot 2025-05-04 at 11.15.57 AM.png",
      "https://unimarkt-bucket.s3.eu-central-1.amazonaws.com/uploads/c7f1b069-d1e8-4518-bf80-fd27f56586d6_Screenshot 2025-05-04 at 11.35.45 AM.png",
      "https://unimarkt-bucket.s3.eu-central-1.amazonaws.com/uploads/c72d695a-ffaf-476f-b4cb-9cf32f368b69_Screenshot 2025-05-04 at 11.34.48 AM.png",
      "https://unimarkt-bucket.s3.eu-central-1.amazonaws.com/uploads/6a048072-464b-4f6a-9f95-7508b02d2e39_Screenshot 2025-05-04 at 11.36.23 AM.png",
      "https://unimarkt-bucket.s3.eu-central-1.amazonaws.com/uploads/d5766193-de9a-4073-b351-a9d2512a4c4e_Screenshot 2025-05-07 at 10.56.22 AM.png",
    ],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "pending",
    created_at: "2025-06-15T13:24:51.315658Z",
    pickup_location: "Iure quam totam laud",
  },
  {
    product_id: "21",
    name: "Martena Ayala 1032pm",
    category: {
      id: "4",
      name: "Clothing",
      color: "#FF69B4",
      slug: "clothing",
      category_id: "4",
      subcategories: [
        {
          id: "3",
          name: "Tshirts",
          color: undefined,
          slug: "tshirts",
          category_id: "4",
          subcategories: [],
        },
        {
          id: "8",
          name: "Jeans",
          color: undefined,
          slug: "jeans",
          category_id: "4",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "8",
      name: "Jeans",
      color: undefined,
      slug: "jeans",
      category_id: "4",
      subcategories: [],
    },
    description: "Est voluptates bland",
    price: "311.00",
    images: [
      "https://your-bucket.s3.amazonaws.com/products/1749933156642-0ybh7-Screenshot 2025-06-05 at 7.36.13 PM.png",
      "https://your-bucket.s3.amazonaws.com/products/1749933157107-zgmv0i-Screenshot 2025-06-03 at 5.49.54 PM.png",
      "https://your-bucket.s3.amazonaws.com/products/1749933155339-59jw26-Screenshot 2025-06-01 at 11.17.12 AM (2).png",
      "https://your-bucket.s3.amazonaws.com/products/1749933155291-ae9pun-Screenshot 2025-06-01 at 11.17.12 AM.png",
    ],
    user: {
      id: "1",
      name: "UniMarkt",
      email: "unimarkt@example.com",
      contact_number: "1234567890",
    },
    status: "approved",
    created_at: "2025-06-14T20:32:42.104515Z",
    pickup_location: "Eveniet est recusan",
  },
  {
    product_id: "19",
    name: "Coffee Table",
    category: {
      id: "5",
      name: "Furniture",
      color: "#A52A2A",
      slug: "furniture",
      category_id: "5",
      subcategories: [
        {
          id: "4",
          name: "Office Furniture",
          color: undefined,
          slug: "office-furniture",
          category_id: "5",
          subcategories: [],
        },
        {
          id: "9",
          name: "Home Furniture",
          color: undefined,
          slug: "home-furniture",
          category_id: "5",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "9",
      name: "Home Furniture",
      color: undefined,
      slug: "home-furniture",
      category_id: "5",
      subcategories: [],
    },
    description: "Wooden coffee table with storage",
    price: "180.00",
    images: ["coffee-table.jpg"],
    user: {
      id: "3",
      name: "Ccin Lee",
      email: "cin@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-19T16:15:00Z",
    pickup_location: "Essen, Germany",
  },
  {
    product_id: "18",
    name: "Winter Coat",
    category: {
      id: "4",
      name: "Clothing",
      color: "#FF69B4",
      slug: "clothing",
      category_id: "4",
      subcategories: [
        {
          id: "3",
          name: "Tshirts",
          color: undefined,
          slug: "tshirts",
          category_id: "4",
          subcategories: [],
        },
        {
          id: "8",
          name: "Jeans",
          color: undefined,
          slug: "jeans",
          category_id: "4",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "3",
      name: "Tshirts",
      color: undefined,
      slug: "tshirts",
      category_id: "4",
      subcategories: [],
    },
    description: "Warm winter parka, size L",
    price: "75.00",
    images: ["winter-coat.jpg"],
    user: {
      id: "1",
      name: "UniMarkt",
      email: "unimarkt@example.com",
      contact_number: "1234567890",
    },
    status: "rejected",
    created_at: "2025-05-18T08:30:00Z",
    pickup_location: "Dortmund, Germany",
  },
  {
    product_id: "17",
    name: "Cookbook Collection",
    category: {
      id: "3",
      name: "Books",
      color: "#8B4513",
      slug: "books",
      category_id: "3",
      subcategories: [
        {
          id: "2",
          name: "Fiction",
          color: undefined,
          slug: "fiction",
          category_id: "3",
          subcategories: [],
        },
        {
          id: "7",
          name: "Non-Fiction",
          color: undefined,
          slug: "non-fiction",
          category_id: "3",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "7",
      name: "Non-Fiction",
      color: undefined,
      slug: "non-fiction",
      category_id: "3",
      subcategories: [],
    },
    description: "Set of 5 Italian cooking books",
    price: "42.00",
    images: ["cookbook-collection.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "pending",
    created_at: "2025-05-17T10:45:00Z",
    pickup_location: "Dresden, Germany",
  },
  {
    product_id: "16",
    name: "Gaming Headset",
    category: {
      id: "2",
      name: "Electronics",
      color: "#0000FF",
      slug: "electronics",
      category_id: "2",
      subcategories: [
        {
          id: "1",
          name: "Mobile Phones",
          color: undefined,
          slug: "mobile-phones",
          category_id: "2",
          subcategories: [],
        },
        {
          id: "6",
          name: "Laptops",
          color: undefined,
          slug: "laptops",
          category_id: "2",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "1",
      name: "Mobile Phones",
      color: undefined,
      slug: "mobile-phones",
      category_id: "2",
      subcategories: [],
    },
    description: "Wireless gaming headset with noise cancellation",
    price: "129.00",
    images: ["gaming-headset.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-16T13:10:00Z",
    pickup_location: "Leipzig, Germany",
  },
  {
    product_id: "15",
    name: "Yoga Mat",
    category: {
      id: "6",
      name: "Sports",
      color: "#228B22",
      slug: "sports",
      category_id: "6",
      subcategories: [
        {
          id: "5",
          name: "Outdoor",
          color: undefined,
          slug: "outdoor",
          category_id: "6",
          subcategories: [],
        },
        {
          id: "10",
          name: "Fitness",
          color: undefined,
          slug: "fitness",
          category_id: "6",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "10",
      name: "Fitness",
      color: undefined,
      slug: "fitness",
      category_id: "6",
      subcategories: [],
    },
    description: "Premium non-slip yoga mat, 6mm thick",
    price: "35.00",
    images: ["yoga-mat.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "rejected",
    created_at: "2025-05-15T11:20:00Z",
    pickup_location: "Bremen, Germany",
  },
  {
    product_id: "14",
    name: "Mountain Bike",
    category: {
      id: "6",
      name: "Sports",
      color: "#228B22",
      slug: "sports",
      category_id: "6",
      subcategories: [
        {
          id: "5",
          name: "Outdoor",
          color: undefined,
          slug: "outdoor",
          category_id: "6",
          subcategories: [],
        },
        {
          id: "10",
          name: "Fitness",
          color: undefined,
          slug: "fitness",
          category_id: "6",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "5",
      name: "Outdoor",
      color: undefined,
      slug: "outdoor",
      category_id: "6",
      subcategories: [],
    },
    description: "Trek mountain bike, 21-speed",
    price: "450.00",
    images: ["mountain-bike.jpg"],
    user: {
      id: "1",
      name: "UniMarkt",
      email: "unimarkt@example.com",
      contact_number: "1234567890",
    },
    status: "pending",
    created_at: "2025-05-14T15:30:00Z",
    pickup_location: "Nürnberg, Germany",
  },
  {
    product_id: "13",
    name: "Standing Desk",
    category: {
      id: "5",
      name: "Furniture",
      color: "#A52A2A",
      slug: "furniture",
      category_id: "5",
      subcategories: [
        {
          id: "4",
          name: "Office Furniture",
          color: undefined,
          slug: "office-furniture",
          category_id: "5",
          subcategories: [],
        },
        {
          id: "9",
          name: "Home Furniture",
          color: undefined,
          slug: "home-furniture",
          category_id: "5",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "4",
      name: "Office Furniture",
      color: undefined,
      slug: "office-furniture",
      category_id: "5",
      subcategories: [],
    },
    description: "Adjustable height standing desk",
    price: "320.00",
    images: ["standing-desk.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-13T12:00:00Z",
    pickup_location: "Fulda, Germany",
  },
  {
    product_id: "12",
    name: "IKEA Sofa",
    category: {
      id: "5",
      name: "Furniture",
      color: "#A52A2A",
      slug: "furniture",
      category_id: "5",
      subcategories: [
        {
          id: "4",
          name: "Office Furniture",
          color: undefined,
          slug: "office-furniture",
          category_id: "5",
          subcategories: [],
        },
        {
          id: "9",
          name: "Home Furniture",
          color: undefined,
          slug: "home-furniture",
          category_id: "5",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "9",
      name: "Home Furniture",
      color: undefined,
      slug: "home-furniture",
      category_id: "5",
      subcategories: [],
    },
    description: "3-seater fabric sofa, light gray",
    price: "299.00",
    images: ["ikea-sofa.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "rejected",
    created_at: "2025-05-12T09:45:00Z",
    pickup_location: "Hannover, Germany",
  },
  {
    product_id: "11",
    name: "Vintage Leather Jacket",
    category: {
      id: "4",
      name: "Clothing",
      color: "#FF69B4",
      slug: "clothing",
      category_id: "4",
      subcategories: [
        {
          id: "3",
          name: "Tshirts",
          color: undefined,
          slug: "tshirts",
          category_id: "4",
          subcategories: [],
        },
        {
          id: "8",
          name: "Jeans",
          color: undefined,
          slug: "jeans",
          category_id: "4",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "3",
      name: "Tshirts",
      color: undefined,
      slug: "tshirts",
      category_id: "4",
      subcategories: [],
    },
    description: "Genuine leather jacket, worn condition",
    price: "89.00",
    images: ["leather-jacket-front.jpg", "leather-jacket-back.jpg"],
    user: {
      id: "3",
      name: "Ccin Lee",
      email: "cin@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-11T14:15:00Z",
    pickup_location: "Düsseldorf, Germany",
  },
  {
    product_id: "10",
    name: "Women's Jeans",
    category: {
      id: "4",
      name: "Clothing",
      color: "#FF69B4",
      slug: "clothing",
      category_id: "4",
      subcategories: [
        {
          id: "3",
          name: "Tshirts",
          color: undefined,
          slug: "tshirts",
          category_id: "4",
          subcategories: [],
        },
        {
          id: "8",
          name: "Jeans",
          color: undefined,
          slug: "jeans",
          category_id: "4",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "8",
      name: "Jeans",
      color: undefined,
      slug: "jeans",
      category_id: "4",
      subcategories: [],
    },
    description: "High-waisted skinny jeans, size 28",
    price: "45.00",
    images: ["womens-jeans.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-10T10:30:00Z",
    pickup_location: "Stuttgart, Germany",
  },
  {
    product_id: "9",
    name: "Sapiens",
    category: {
      id: "3",
      name: "Books",
      color: "#8B4513",
      slug: "books",
      category_id: "3",
      subcategories: [
        {
          id: "2",
          name: "Fiction",
          color: undefined,
          slug: "fiction",
          category_id: "3",
          subcategories: [],
        },
        {
          id: "7",
          name: "Non-Fiction",
          color: undefined,
          slug: "non-fiction",
          category_id: "3",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "7",
      name: "Non-Fiction",
      color: undefined,
      slug: "non-fiction",
      category_id: "3",
      subcategories: [],
    },
    description: "A Brief History of Humankind by Yuval Noah Harari",
    price: "18.00",
    images: ["sapiens-cover.jpg"],
    user: {
      id: "4",
      name: "Dinn Lee",
      email: "din@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-09T16:20:00Z",
    pickup_location: "Köln, Germany",
  },
  {
    product_id: "8",
    name: "1984",
    category: {
      id: "3",
      name: "Books",
      color: "#8B4513",
      slug: "books",
      category_id: "3",
      subcategories: [
        {
          id: "2",
          name: "Fiction",
          color: undefined,
          slug: "fiction",
          category_id: "3",
          subcategories: [],
        },
        {
          id: "7",
          name: "Non-Fiction",
          color: undefined,
          slug: "non-fiction",
          category_id: "3",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "2",
      name: "Fiction",
      color: undefined,
      slug: "fiction",
      category_id: "3",
      subcategories: [],
    },
    description: "Dystopian novel by George Orwell",
    price: "12.50",
    images: ["1984-cover.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-08T13:45:00Z",
    pickup_location: "Hamburg, Germany",
  },
  {
    product_id: "7",
    name: "MacBook Pro 14",
    category: {
      id: "2",
      name: "Electronics",
      color: "#0000FF",
      slug: "electronics",
      category_id: "2",
      subcategories: [
        {
          id: "1",
          name: "Mobile Phones",
          color: undefined,
          slug: "mobile-phones",
          category_id: "2",
          subcategories: [],
        },
        {
          id: "6",
          name: "Laptops",
          color: undefined,
          slug: "laptops",
          category_id: "2",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "6",
      name: "Laptops",
      color: undefined,
      slug: "laptops",
      category_id: "2",
      subcategories: [],
    },
    description: "Apple MacBook Pro with M2 chip",
    price: "1899.00",
    images: ["macbook-pro-14.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-07T08:15:00Z",
    pickup_location: "Berlin, Germany",
  },
  {
    product_id: "6",
    name: "Samsung Galaxy S22",
    category: {
      id: "2",
      name: "Electronics",
      color: "#0000FF",
      slug: "electronics",
      category_id: "2",
      subcategories: [
        {
          id: "1",
          name: "Mobile Phones",
          color: undefined,
          slug: "mobile-phones",
          category_id: "2",
          subcategories: [],
        },
        {
          id: "6",
          name: "Laptops",
          color: undefined,
          slug: "laptops",
          category_id: "2",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "1",
      name: "Mobile Phones",
      color: undefined,
      slug: "mobile-phones",
      category_id: "2",
      subcategories: [],
    },
    description: "High-performance Android smartphone",
    price: "699.99",
    images: ["galaxy-s22-front.jpg", "galaxy-s22-back.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-06T11:30:00Z",
    pickup_location: "München, Germany",
  },
  {
    product_id: "5",
    name: "Tent",
    category: {
      id: "5",
      name: "Furniture",
      color: "#A52A2A",
      slug: "furniture",
      category_id: "5",
      subcategories: [
        {
          id: "4",
          name: "Office Furniture",
          color: undefined,
          slug: "office-furniture",
          category_id: "5",
          subcategories: [],
        },
        {
          id: "9",
          name: "Home Furniture",
          color: undefined,
          slug: "home-furniture",
          category_id: "5",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "5",
      name: "Outdoor",
      color: undefined,
      slug: "outdoor",
      category_id: "6",
      subcategories: [],
    },
    description: "4-person outdoor camping tent",
    price: "120.00",
    images: ["tent1.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-05T16:00:00Z",
    pickup_location: "Fulda, Germany",
  },
  {
    product_id: "4",
    name: "Office Chair",
    category: {
      id: "4",
      name: "Clothing",
      color: "#FF69B4",
      slug: "clothing",
      category_id: "4",
      subcategories: [
        {
          id: "3",
          name: "Tshirts",
          color: undefined,
          slug: "tshirts",
          category_id: "4",
          subcategories: [],
        },
        {
          id: "8",
          name: "Jeans",
          color: undefined,
          slug: "jeans",
          category_id: "4",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "4",
      name: "Office Furniture",
      color: undefined,
      slug: "office-furniture",
      category_id: "5",
      subcategories: [],
    },
    description: "Ergonomic office chair",
    price: "150.00",
    images: ["chair1.jpg"],
    user: {
      id: "4",
      name: "Dinn Lee",
      email: "din@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-04T09:00:00Z",
    pickup_location: "Fulda, Germany",
  },
  {
    product_id: "3",
    name: "Men's T-Shirt",
    category: {
      id: "3",
      name: "Books",
      color: "#8B4513",
      slug: "books",
      category_id: "3",
      subcategories: [
        {
          id: "2",
          name: "Fiction",
          color: undefined,
          slug: "fiction",
          category_id: "3",
          subcategories: [],
        },
        {
          id: "7",
          name: "Non-Fiction",
          color: undefined,
          slug: "non-fiction",
          category_id: "3",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "3",
      name: "Tshirts",
      color: undefined,
      slug: "tshirts",
      category_id: "4",
      subcategories: [],
    },
    description: "Comfortable cotton t-shirt",
    price: "20.00",
    images: ["tshirt-front.jpg", "tshirt-back.jpg"],
    user: {
      id: "4",
      name: "Dinn Lee",
      email: "din@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-03T14:00:00Z",
    pickup_location: "Kasele, Germany",
  },
  {
    product_id: "2",
    name: "The Great Gatsby",
    category: {
      id: "2",
      name: "Electronics",
      color: "#0000FF",
      slug: "electronics",
      category_id: "2",
      subcategories: [
        {
          id: "1",
          name: "Mobile Phones",
          color: undefined,
          slug: "mobile-phones",
          category_id: "2",
          subcategories: [],
        },
        {
          id: "6",
          name: "Laptops",
          color: undefined,
          slug: "laptops",
          category_id: "2",
          subcategories: [],
        },
      ],
    },
    sub_category: {
      id: "2",
      name: "Fiction",
      color: undefined,
      slug: "fiction",
      category_id: "3",
      subcategories: [],
    },
    description: "Classic novel by F. Scott Fitzgerald",
    price: "15.00",
    images: ["gatsby-cover.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-02T12:00:00Z",
    pickup_location: "Frankfurt, Germany",
  },
  {
    product_id: "1",
    name: "iPhone 13",
    category: {
      id: "1",
      name: "All",
      color: "#CCCCCC",
      slug: "all",
      category_id: "1",
      subcategories: [],
    },
    sub_category: {
      id: "1",
      name: "Mobile Phones",
      color: undefined,
      slug: "mobile-phones",
      category_id: "2",
      subcategories: [],
    },
    description: "Latest Apple iPhone 13",
    price: "799.99",
    images: ["iphone13-front.jpg", "iphone13-back.jpg"],
    user: {
      id: "2",
      name: "Bob Lee",
      email: "bob@example.com",
      contact_number: "0987654321",
    },
    status: "approved",
    created_at: "2025-05-01T10:00:00Z",
    pickup_location: "Fulda, Germany",
  },
];
