import { UserApproval } from "@/modules/admin/ui/views/admin-admins-table";

export const users: UserApproval[] = [
  // ----- Basic Users -----
  {
    id: "u001",
    name: "Anna Becker",
    email: "anna.becker@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u002",
    name: "Jonas Müller",
    email: "jonas.mueller@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u003",
    name: "Mila Schneider",
    email: "mila.schneider@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u004",
    name: "Lukas Weber",
    email: "lukas.weber@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u005",
    name: "Nina Wagner",
    email: "nina.wagner@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u006",
    name: "Tim Fischer",
    email: "tim.fischer@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u007",
    name: "Sophie Hoffmann",
    email: "sophie.hoffmann@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u008",
    name: "Felix Schäfer",
    email: "felix.schaefer@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u009",
    name: "Emily Koch",
    email: "emily.koch@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u010",
    name: "Leon Schröder",
    email: "leon.schroeder@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u011",
    name: "Marie Wolf",
    email: "marie.wolf@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u012",
    name: "Noah Zimmermann",
    email: "noah.zimmermann@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u013",
    name: "Lara Hartmann",
    email: "lara.hartmann@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u014",
    name: "Ben Lange",
    email: "ben.lange@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },
  {
    id: "u015",
    name: "Clara Schmitt",
    email: "clara.schmitt@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: [],
    status: "approved",
  },

  // ----- Faculty Requests -----
  {
    id: "u016",
    name: "Prof. David Klein",
    email: "david.klein@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u017",
    name: "Prof. Jana Weiß",
    email: "jana.weiss@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u018",
    name: "Dr. Paul Meier",
    email: "paul.meier@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u019",
    name: "Prof. Lisa Braun",
    email: "lisa.braun@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u020",
    name: "Dr. Thomas König",
    email: "thomas.koenig@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u021",
    name: "Prof. Eva Neumann",
    email: "eva.neumann@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u022",
    name: "Dr. Martin Scholz",
    email: "martin.scholz@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u023",
    name: "Prof. Anna Keller",
    email: "anna.keller@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u024",
    name: "Dr. Michael Busch",
    email: "michael.busch@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u025",
    name: "Prof. Julia Sauer",
    email: "julia.sauer@hs-fulda.de",
    requestedRoles: ["faculty"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u026",
    name: "Dr. Peter Maurer",
    email: "peter.maurer@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["faculty"],
    status: "approved",
  },
  {
    id: "u027",
    name: "Prof. Nadine Frank",
    email: "nadine.frank@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["faculty"],
    status: "approved",
  },
  {
    id: "u028",
    name: "Dr. Jan Weber",
    email: "jan.weber@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["faculty"],
    status: "approved",
  },
  {
    id: "u029",
    name: "Prof. Claudia Dietrich",
    email: "claudia.dietrich@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["faculty"],
    status: "approved",
  },
  {
    id: "u030",
    name: "Dr. Robert Albrecht",
    email: "robert.albrecht@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["faculty"],
    status: "approved",
  },

  // ----- Requests -----
  {
    id: "u031",
    name: "Felix Lang",
    email: "felix.lang@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u032",
    name: "Sarah Blum",
    email: "sarah.blum@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u033",
    name: "Jonas Hahn",
    email: "jonas.hahn@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u034",
    name: "Lara Schwarz",
    email: "lara.schwarz@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u035",
    name: "Tim Zimmer",
    email: "tim.zimmer@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u036",
    name: "Sophie Vogt",
    email: "sophie.vogt@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u037",
    name: "Leon Busch",
    email: "leon.busch@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u038",
    name: "Clara Böhme",
    email: "clara.boehme@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u039",
    name: "Ben Winter",
    email: "ben.winter@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u040",
    name: "Mia Albers",
    email: "mia.albers@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u041",
    name: "Noah Dietz",
    email: "noah.dietz@hs-fulda.de",
    requestedRoles: ["admin"],
    approvedRoles: [],
    status: "pending",
  },
  {
    id: "u042",
    name: "Lina Graf",
    email: "lina.graf@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["admin"],
    status: "approved",
  },
  {
    id: "u043",
    name: "Tom Arnold",
    email: "tom.arnold@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["admin"],
    status: "approved",
  },
  {
    id: "u044",
    name: "Emma Groß",
    email: "emma.gross@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["admin"],
    status: "approved",
  },
  {
    id: "u045",
    name: "Paul Engel",
    email: "paul.engel@hs-fulda.de",
    requestedRoles: [],
    approvedRoles: ["admin"],
    status: "approved",
  },
];
